2020-10-27 21:43:42,386 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:43:42,756 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:43:42,794 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:43:43,150 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:43:43,157 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:43:43,471 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:43:43,477 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:43:43,709 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:43:43,718 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:43:43,724 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:43:43,868 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:43:43,872 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:43:44,001 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 21:52:34,008 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:52:34,357 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:52:34,392 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:34,727 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:52:34,736 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:35,105 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:52:35,110 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:35,359 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:52:35,367 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:52:35,371 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:35,505 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:52:35,510 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:35,630 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 21:52:58,350 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:52:58,702 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:52:58,743 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:59,065 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:52:59,074 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:59,408 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:52:59,413 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:59,598 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:52:59,605 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:52:59,609 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:59,730 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:52:59,734 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:52:59,857 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 21:55:59,260 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:55:59,612 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:55:59,648 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:00,055 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:56:00,063 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:00,370 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:56:00,375 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:00,902 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:56:00,910 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:56:00,916 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:01,041 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:56:01,046 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:01,179 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 21:56:38,408 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:56:38,760 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:56:38,796 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:39,182 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:56:39,189 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:39,607 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:56:39,613 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:39,807 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:56:39,815 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:56:39,819 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:39,944 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:56:39,949 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:56:40,100 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 21:57:16,711 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:57:17,082 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:57:17,119 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:57:17,468 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:57:17,476 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:57:17,800 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:57:17,805 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:57:18,025 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:57:18,033 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:57:18,038 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:57:18,165 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:57:18,169 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:57:18,314 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 21:59:00,683 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 21:59:01,071 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:59:01,108 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:59:01,471 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:59:01,479 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:59:01,872 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 21:59:01,877 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:59:02,057 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 21:59:02,064 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 21:59:02,069 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:59:02,204 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 21:59:02,208 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 21:59:02,395 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:03:24,115 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:03:24,490 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:03:24,527 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:24,894 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:03:24,902 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:25,235 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:03:25,240 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:25,430 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:03:25,438 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:03:25,442 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:25,573 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:03:25,577 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:25,717 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:03:55,198 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:03:55,576 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:03:55,614 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:56,045 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:03:56,054 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:56,360 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:03:56,365 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:56,564 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:03:56,571 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:03:56,576 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:56,772 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:03:56,777 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:03:56,912 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:04:11,870 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:04:12,254 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:04:12,289 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:12,589 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:04:12,598 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:12,894 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:04:12,900 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:13,126 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:04:13,136 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:04:13,140 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:13,271 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:04:13,277 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:13,408 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:04:40,847 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 22:04:43,934 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:44,170 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-27 22:04:44,185 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:44,394 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 200 None
2020-10-27 22:04:44,407 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:44,632 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 200 None
2020-10-27 22:04:44,641 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:44,844 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 200 None
2020-10-27 22:04:44,853 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:45,057 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 200 None
2020-10-27 22:04:45,066 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:04:45,306 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 200 None
2020-10-27 22:06:22,673 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:06:57,494 django.request ERROR    Internal Server Error: /admin/logout/
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 251, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 376, in logout
    return LogoutView.as_view(**defaults)(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\views.py", line 119, in dispatch
    next_page = self.get_next_page()
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\views.py", line 133, in get_next_page
    next_page = resolve_url(settings.LOGOUT_REDIRECT_URL)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\shortcuts.py", line 131, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\urls\resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'browse' not found. 'browse' is not a valid view function or pattern name.
2020-10-27 22:07:11,215 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:11,439 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/U8C69ISrhGTTubjqoVgZYg HTTP/1.1" 200 None
2020-10-27 22:07:11,450 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:11,682 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/wp5BpfUi9Aa4T0Gk0bnhag HTTP/1.1" 200 None
2020-10-27 22:07:11,690 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:11,902 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/MHbxF-ZS918-ZoXKQPBEyg HTTP/1.1" 200 None
2020-10-27 22:07:11,911 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:12,149 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/c76v7CGWWjWj__18Mv2j5w HTTP/1.1" 200 None
2020-10-27 22:07:12,160 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:12,411 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/kKSZT7BJ5VH6hCaGlJ52tg HTTP/1.1" 200 None
2020-10-27 22:07:36,488 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:36,723 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/U8C69ISrhGTTubjqoVgZYg HTTP/1.1" 200 None
2020-10-27 22:07:36,733 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:36,952 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/wp5BpfUi9Aa4T0Gk0bnhag HTTP/1.1" 200 None
2020-10-27 22:07:36,961 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:37,180 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/MHbxF-ZS918-ZoXKQPBEyg HTTP/1.1" 200 None
2020-10-27 22:07:37,188 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:37,417 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/c76v7CGWWjWj__18Mv2j5w HTTP/1.1" 200 None
2020-10-27 22:07:37,426 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:07:37,599 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/kKSZT7BJ5VH6hCaGlJ52tg HTTP/1.1" 200 None
2020-10-27 22:08:17,522 django.request ERROR    Internal Server Error: /admin/logout/
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 251, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 376, in logout
    return LogoutView.as_view(**defaults)(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\views.py", line 119, in dispatch
    next_page = self.get_next_page()
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\views.py", line 133, in get_next_page
    next_page = resolve_url(settings.LOGOUT_REDIRECT_URL)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\shortcuts.py", line 131, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\urls\resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'browse' not found. 'browse' is not a valid view function or pattern name.
2020-10-27 22:08:36,864 django.request ERROR    Internal Server Error: /admin/logout/
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 251, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py", line 376, in logout
    return LogoutView.as_view(**defaults)(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\views.py", line 119, in dispatch
    next_page = self.get_next_page()
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\views.py", line 133, in get_next_page
    next_page = resolve_url(settings.LOGOUT_REDIRECT_URL)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\shortcuts.py", line 131, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\urls\resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'browse' not found. 'browse' is not a valid view function or pattern name.
2020-10-27 22:09:34,298 django.request WARNING  Not Found: /browse
2020-10-27 22:09:40,012 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:40,248 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-27 22:09:40,257 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:40,452 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 200 None
2020-10-27 22:09:40,460 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:40,689 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 200 None
2020-10-27 22:09:40,697 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:40,875 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 200 None
2020-10-27 22:09:40,883 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:41,099 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 200 None
2020-10-27 22:09:41,107 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:41,355 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 200 None
2020-10-27 22:09:42,559 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:42,769 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/FaebPpZ8fKuvPtMOZ_dslw HTTP/1.1" 200 None
2020-10-27 22:09:42,779 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:42,977 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/yWn06c7BmeVsoHBxLbnAsA HTTP/1.1" 200 None
2020-10-27 22:09:42,989 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:43,184 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/F1cTAyVghrMagxFHikwQKQ HTTP/1.1" 200 None
2020-10-27 22:09:43,193 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:43,423 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ysFjhHDTuYnTv6wrvsgsWg HTTP/1.1" 200 None
2020-10-27 22:09:43,432 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:43,652 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/RQojRzAYA9Cq87PqwQq5yg HTTP/1.1" 200 None
2020-10-27 22:09:43,661 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:43,889 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rrDymUQnu95UnZtTeeHfnA HTTP/1.1" 200 None
2020-10-27 22:09:50,080 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:50,283 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/FaebPpZ8fKuvPtMOZ_dslw HTTP/1.1" 200 None
2020-10-27 22:09:50,287 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:09:50,517 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/FaebPpZ8fKuvPtMOZ_dslw/reviews HTTP/1.1" 200 None
2020-10-27 22:10:40,286 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:10:40,504 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-27 22:10:40,508 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:10:40,703 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-27 22:10:50,984 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:10:51,202 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/THKnKxcaYAW4ItT8HMZvhA HTTP/1.1" 200 None
2020-10-27 22:10:51,211 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:10:51,393 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/J0OeDwmh5JBhid0A5GvltA HTTP/1.1" 200 None
2020-10-27 22:11:28,519 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:28,762 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/hk9nwr4U0XcV4Rig27WYag HTTP/1.1" 200 None
2020-10-27 22:11:28,772 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:29,000 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/jhvlGPnHMZYJUMrc2XrSDg HTTP/1.1" 200 None
2020-10-27 22:11:29,010 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:29,220 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/T8mtnmYVkKI6pYwRoMitYQ HTTP/1.1" 200 None
2020-10-27 22:11:29,231 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:29,492 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/0PJqBtI5y_RPldLlu6Ev2g HTTP/1.1" 200 None
2020-10-27 22:11:29,505 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:29,732 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/34LM8_lP8iwizHBu6YgaQQ HTTP/1.1" 200 None
2020-10-27 22:11:29,760 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:29,966 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:29,977 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:30,205 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:30,214 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:30,454 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/Ece_DRuD1yQjRPJBAebRpw HTTP/1.1" 200 None
2020-10-27 22:11:30,464 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:30,668 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qpD22cY8CSXLT2qujiJtqw HTTP/1.1" 200 None
2020-10-27 22:11:30,678 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:30,883 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/W2sR69xVLzMI_CXJXk-PZg HTTP/1.1" 200 None
2020-10-27 22:11:30,892 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:31,438 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/mpD_kUFo8POQDLoLgRSfCg HTTP/1.1" 200 None
2020-10-27 22:11:37,398 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:37,676 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:37,679 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:37,957 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:11:40,223 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:40,435 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:40,440 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:40,669 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:11:46,051 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:46,307 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:46,310 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:46,527 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:11:53,924 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:54,137 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:54,141 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:54,405 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:11:59,588 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:11:59,832 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:11:59,836 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:00,083 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:12:12,268 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:12,519 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:12:12,522 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:12,735 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:12:14,208 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:14,425 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:12:14,429 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:14,756 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:12:19,511 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:19,784 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:12:19,789 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:20,009 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:12:24,096 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:24,311 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q HTTP/1.1" 200 None
2020-10-27 22:12:24,314 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:12:24,528 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/7wo8Pt6M2DcUxslJ1YhA5Q/reviews HTTP/1.1" 200 None
2020-10-27 22:13:38,986 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:13:39,356 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:13:39,396 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:13:39,794 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:13:39,802 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:13:40,133 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:13:40,138 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:13:40,344 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:13:40,350 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:13:40,355 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:13:40,482 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:13:40,489 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:13:40,689 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:20:29,618 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:20:29,989 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:20:30,026 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:30,386 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:20:30,394 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:30,742 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:20:30,747 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:30,948 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:20:30,955 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:20:30,961 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:31,085 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:20:31,090 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:31,230 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:20:51,342 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:20:51,732 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:20:51,770 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:52,113 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:20:52,121 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:52,472 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:20:52,477 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:52,678 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:20:52,689 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:20:52,698 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:52,850 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:20:52,855 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:20:52,993 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:21:33,471 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:21:33,870 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:21:33,908 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:21:34,285 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:21:34,292 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:21:34,649 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:21:34,655 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:21:34,892 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:21:34,900 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:21:34,905 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:21:35,046 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:21:35,050 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:21:35,168 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:30:13,880 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:30:14,260 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:30:14,297 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:30:14,695 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:30:14,703 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:30:15,044 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:30:15,050 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:30:15,273 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:30:15,284 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:30:15,288 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:30:15,417 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:30:15,421 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:30:15,551 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:30:15,573 django.request WARNING  Not Found: /user/reset_password
2020-10-27 22:35:13,231 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:35:13,599 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:35:13,637 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:14,012 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:35:14,020 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:14,328 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:35:14,333 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:14,595 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:35:14,605 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:35:14,609 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:14,729 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:35:14,734 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:14,861 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:35:39,982 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:35:40,360 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:35:40,401 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:40,762 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:35:40,772 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:41,085 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:35:41,091 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:41,281 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:35:41,290 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:35:41,295 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:41,409 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:35:41,414 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:35:41,542 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:36:08,317 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:36:08,678 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:36:08,715 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:36:09,044 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:36:09,052 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:36:09,419 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:36:09,425 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:36:09,663 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:36:09,670 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:36:09,676 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:36:09,802 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:36:09,808 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:36:09,945 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:38:22,537 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\user\views.py changed, reloading.
2020-10-27 22:38:22,538 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:38:23,456 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 22:39:56,838 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\user\views.py changed, reloading.
2020-10-27 22:39:56,839 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:39:57,674 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 22:40:55,238 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:40:55,450 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/U8C69ISrhGTTubjqoVgZYg HTTP/1.1" 200 None
2020-10-27 22:40:55,460 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:40:55,693 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/wp5BpfUi9Aa4T0Gk0bnhag HTTP/1.1" 200 None
2020-10-27 22:40:55,702 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:40:55,945 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/MHbxF-ZS918-ZoXKQPBEyg HTTP/1.1" 200 None
2020-10-27 22:40:55,959 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:40:56,172 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/c76v7CGWWjWj__18Mv2j5w HTTP/1.1" 200 None
2020-10-27 22:40:56,183 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:40:56,374 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/kKSZT7BJ5VH6hCaGlJ52tg HTTP/1.1" 200 None
2020-10-27 22:43:33,322 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\user\views.py changed, reloading.
2020-10-27 22:43:33,323 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:43:34,145 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 22:44:48,886 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\user\views.py changed, reloading.
2020-10-27 22:44:48,888 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:44:49,721 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 22:47:30,138 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\user\views.py changed, reloading.
2020-10-27 22:47:30,139 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:47:30,950 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 22:55:36,118 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:55:52,277 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:56:01,418 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:56:04,874 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:56:05,236 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:56:05,286 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:56:05,707 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:56:05,715 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:56:06,081 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 22:56:06,086 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:56:06,351 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 22:56:06,358 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 22:56:06,362 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:56:06,474 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 22:56:06,478 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 22:56:06,615 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 22:57:07,277 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\user\views.py changed, reloading.
2020-10-27 22:57:07,278 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 22:57:08,058 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 23:08:26,449 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 23:08:26,814 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 23:08:26,852 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:08:27,317 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 23:08:27,326 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:08:27,652 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 23:08:27,657 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:08:27,873 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 23:08:27,880 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 23:08:27,885 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:08:28,011 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 23:08:28,016 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:08:28,144 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-27 23:36:58,499 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\models.py changed, reloading.
2020-10-27 23:36:58,501 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 23:36:59,300 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-27 23:46:00,286 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-27 23:46:00,649 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 23:46:00,684 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:46:01,023 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 23:46:01,030 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:46:01,370 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw HTTP/1.1" 200 None
2020-10-27 23:46:01,375 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:46:01,581 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/WavvLdfdP6g8aZTtbBQHTw/reviews HTTP/1.1" 200 None
2020-10-27 23:46:01,590 restaurant.views WARNING  Restaurant ID could not be found: -1
2020-10-27 23:46:01,594 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:46:01,720 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16 HTTP/1.1" 404 102
2020-10-27 23:46:01,728 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-27 23:46:02,145 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/16/reviews HTTP/1.1" 404 102
2020-10-30 21:35:40,553 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-30 21:35:54,060 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-30 21:35:54,061 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-30 21:35:54,823 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-30 21:36:11,582 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\urls.py changed, reloading.
2020-10-30 21:36:11,583 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-30 21:36:12,338 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-30 21:36:14,052 django.request WARNING  Not Found: /
2020-10-30 21:36:14,176 django.request WARNING  Not Found: /favicon.ico
2020-10-30 21:36:17,472 django.request WARNING  Not Found: /restaurant/
2020-10-30 21:36:25,972 django.request ERROR    Internal Server Error: /restaurant/profile/7/
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: restaurant_restaurant

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py", line 20, in get_restaurant_profile
    restaurant = Restaurant.objects.get(pk=restaurant_id)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 425, in get
    num = len(clone)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 269, in __len__
    self._fetch_all()
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: restaurant_restaurant
2020-10-31 02:10:45,849 django.request ERROR    Internal Server Error: /restaurant/profile/7/
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: restaurant_restaurant

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py", line 20, in get_restaurant_profile
    restaurant = Restaurant.objects.get(pk=restaurant_id)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 425, in get
    num = len(clone)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 269, in __len__
    self._fetch_all()
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: restaurant_restaurant
2020-10-31 02:11:09,139 django.request ERROR    Internal Server Error: /restaurant/profile/4/
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: restaurant_restaurant

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py", line 20, in get_restaurant_profile
    restaurant = Restaurant.objects.get(pk=restaurant_id)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 425, in get
    num = len(clone)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 269, in __len__
    self._fetch_all()
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: restaurant_restaurant
2020-10-31 02:16:18,960 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 02:16:25,644 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 02:16:29,387 restaurant.views WARNING  Restaurant ID could not be found: 4
2020-10-31 02:16:29,388 django.request WARNING  Not Found: /restaurant/profile/4/
2020-10-31 02:16:33,582 restaurant.views WARNING  Restaurant ID could not be found: 5
2020-10-31 02:16:33,583 django.request WARNING  Not Found: /restaurant/profile/5/
2020-10-31 02:40:27,506 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 02:40:32,687 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 02:40:36,032 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 02:40:36,245 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/kKSZT7BJ5VH6hCaGlJ52tg HTTP/1.1" 200 None
2020-10-31 02:40:36,249 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 02:40:36,528 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/kKSZT7BJ5VH6hCaGlJ52tg/reviews HTTP/1.1" 200 None
2020-10-31 17:30:47,703 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 17:30:51,890 django.request WARNING  Not Found: /
2020-10-31 17:30:51,994 django.request WARNING  Not Found: /favicon.ico
2020-10-31 17:30:58,962 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 17:30:59,246 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 17:30:59,251 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 17:30:59,449 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 20:17:20,494 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 20:17:20,724 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 20:17:20,728 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 20:17:20,944 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 20:19:26,177 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 20:19:26,406 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 20:19:26,409 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 20:19:26,620 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 20:20:23,114 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 20:20:23,333 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 20:20:23,337 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 20:20:23,547 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 20:22:59,675 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\models.py changed, reloading.
2020-10-31 20:22:59,676 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 20:23:00,476 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 20:30:29,138 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\models.py changed, reloading.
2020-10-31 20:30:29,139 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 20:30:29,962 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 21:08:13,158 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:08:13,399 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:08:13,405 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:08:13,647 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:22:12,154 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:22:12,384 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:22:12,388 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:22:12,582 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:23:34,970 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:23:35,181 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:23:35,184 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:23:35,380 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:24:53,495 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:24:53,734 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:24:53,738 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:24:53,949 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:34:45,320 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:34:45,517 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:34:45,520 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:34:45,738 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:41:26,020 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:41:26,226 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:41:26,230 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:41:26,449 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:53:08,411 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:53:08,623 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:53:08,626 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:53:08,821 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 21:53:19,255 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:53:19,462 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 21:53:19,465 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 21:53:19,697 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 22:00:29,223 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:00:29,682 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 22:00:29,686 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:00:29,890 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 22:00:29,947 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:00:29,971 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:07:00,750 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:07:01,036 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 22:07:01,051 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:07:01,246 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 22:07:01,287 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:07:01,323 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:11:25,636 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:11:25,924 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 22:11:25,927 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:11:26,221 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 22:11:26,261 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:11:26,296 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:11:35,833 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:11:36,099 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 22:11:36,103 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 22:11:36,305 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 22:11:36,350 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:11:36,371 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 22:22:21,958 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-31 22:22:21,960 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 22:22:22,771 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 22:22:30,117 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-31 22:22:30,118 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 22:22:30,862 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 22:50:56,418 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-31 22:50:56,419 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 22:50:57,197 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 23:06:26,144 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-31 23:06:26,144 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 23:06:26,917 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 23:16:40,365 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-31 23:16:40,367 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 23:16:41,161 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 23:32:53,365 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-10-31 23:32:53,366 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 23:32:54,116 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 23:33:07,650 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\forms.py changed, reloading.
2020-10-31 23:33:07,651 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 23:33:08,427 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 23:33:59,830 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\forms.py changed, reloading.
2020-10-31 23:33:59,832 asyncio      DEBUG    Using proactor: IocpProactor
2020-10-31 23:34:00,567 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-10-31 23:34:03,054 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 23:34:03,302 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 23:34:03,305 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 23:34:03,555 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 23:34:03,639 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 23:34:03,663 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 23:37:20,212 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 23:37:20,437 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 23:37:20,440 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 23:37:20,641 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 23:37:20,690 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 23:37:20,715 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 23:38:22,244 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 23:38:22,531 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-10-31 23:38:22,534 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-10-31 23:38:22,735 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-10-31 23:38:22,771 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-10-31 23:38:22,819 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 15:42:00,955 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 15:42:02,508 django.request WARNING  Not Found: /
2020-11-01 15:42:02,605 django.request WARNING  Not Found: /favicon.ico
2020-11-01 15:42:09,874 django.request WARNING  Not Found: /restaurant/pr'
2020-11-01 15:42:13,197 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 15:42:13,334 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 15:42:13,351 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 15:42:13,448 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 429 230
2020-11-01 15:42:13,548 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 15:42:13,587 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:16:01,226 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\urls.py changed, reloading.
2020-11-01 16:16:01,226 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:16:02,038 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 16:31:52,437 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\urls.py changed, reloading.
2020-11-01 16:31:52,438 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:31:53,195 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 16:31:54,941 django.request WARNING  Not Found: /
2020-11-01 16:32:04,437 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:04,549 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:32:04,552 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:04,646 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 429 230
2020-11-01 16:32:04,693 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:32:04,728 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:32:14,663 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:14,792 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:32:14,801 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:14,904 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 429 230
2020-11-01 16:32:14,912 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:15,005 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 429 230
2020-11-01 16:32:15,013 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:15,116 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 429 230
2020-11-01 16:32:15,124 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:15,219 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 429 230
2020-11-01 16:32:15,227 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:15,345 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 429 230
2020-11-01 16:32:26,877 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:27,034 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:32:27,043 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:27,146 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 429 230
2020-11-01 16:32:27,154 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:27,238 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 429 230
2020-11-01 16:32:27,247 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:27,349 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 429 230
2020-11-01 16:32:27,358 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:27,451 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 429 230
2020-11-01 16:32:27,478 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:32:27,568 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 429 230
2020-11-01 16:32:33,280 django.request ERROR    Internal Server Error: /restaurant/browse/detail.html
Traceback (most recent call last):
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Legen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py", line 68, in get_landing_page
    restaurant_list = get_restaurant_list(page, 6)
  File "C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\utils.py", line 66, in get_restaurant_list
    offset = int(page) * int(limit)
ValueError: invalid literal for int() with base 10: 'detail.html'
2020-11-01 16:32:56,743 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:33:05,324 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:33:27,897 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:33:32,604 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:39:17,344 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:41:44,911 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:42:28,715 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:42:49,590 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:43:19,828 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:43:30,498 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:43:42,872 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:44:16,283 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 16:44:17,731 django.request WARNING  Not Found: /
2020-11-01 16:44:23,794 django.request WARNING  Not Found: /restaurant/
2020-11-01 16:44:28,747 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:28,847 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:44:28,851 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:28,976 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 429 230
2020-11-01 16:44:29,036 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:44:29,100 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:44:31,529 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:31,645 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:44:31,655 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:31,739 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 429 230
2020-11-01 16:44:31,747 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:31,836 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 429 230
2020-11-01 16:44:31,844 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:31,942 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 429 230
2020-11-01 16:44:31,950 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:32,042 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 429 230
2020-11-01 16:44:32,050 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:44:32,158 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 429 230
2020-11-01 16:44:41,516 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:44:41,566 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:44:59,378 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:45:02,035 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:45:06,944 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:45:10,950 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:45:47,413 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 16:45:48,960 django.request WARNING  Not Found: /
2020-11-01 16:46:30,476 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:46:30,530 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:46:53,530 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:46:57,906 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:47:01,718 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:47:27,431 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 16:47:28,811 django.request WARNING  Not Found: /
2020-11-01 16:47:37,770 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:37,871 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:47:37,874 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:37,966 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 429 230
2020-11-01 16:47:38,019 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:47:38,431 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 16:47:41,511 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:41,603 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:47:41,614 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:41,702 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 429 230
2020-11-01 16:47:41,710 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:41,811 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 429 230
2020-11-01 16:47:41,819 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:41,914 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 429 230
2020-11-01 16:47:41,922 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:42,023 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 429 230
2020-11-01 16:47:42,032 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:47:42,120 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 429 230
2020-11-01 16:48:03,368 django.request WARNING  Not Found: /restaurant/inspection_records/
2020-11-01 16:48:14,421 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:48:14,541 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:48:14,552 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:48:14,640 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 429 230
2020-11-01 16:48:14,649 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:48:14,738 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 429 230
2020-11-01 16:48:14,749 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:48:14,849 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 429 230
2020-11-01 16:48:14,857 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:48:14,955 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 429 230
2020-11-01 16:48:14,964 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:48:15,060 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 429 230
2020-11-01 16:48:54,133 django.request WARNING  Not Found: /restaurant/inspection_records/
2020-11-01 16:49:22,302 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:49:22,404 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 429 230
2020-11-01 16:49:22,413 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:49:22,504 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 429 230
2020-11-01 16:49:22,514 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:49:22,606 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 429 230
2020-11-01 16:49:22,614 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:49:22,986 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 429 230
2020-11-01 16:49:22,994 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:49:23,095 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 429 230
2020-11-01 16:49:23,106 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:49:23,204 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 429 230
2020-11-01 16:52:55,681 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\dinesafelysite\settings.py changed, reloading.
2020-11-01 16:52:55,683 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 16:52:56,503 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 16:53:05,047 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:05,293 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-11-01 16:53:05,307 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:05,509 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 200 None
2020-11-01 16:53:05,518 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:05,778 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 200 None
2020-11-01 16:53:05,788 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:05,977 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 200 None
2020-11-01 16:53:05,985 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:06,225 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 200 None
2020-11-01 16:53:06,235 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:06,478 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 200 None
2020-11-01 16:53:08,953 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:09,187 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-11-01 16:53:09,191 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 16:53:09,414 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig/reviews HTTP/1.1" 200 None
2020-11-01 16:53:09,459 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 18:57:29,202 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:29,458 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/qI18SQBMcNTNo4ZqosfEig HTTP/1.1" 200 None
2020-11-01 18:57:29,467 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:29,685 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 200 None
2020-11-01 18:57:29,695 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:29,913 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/sog3etuV8CwqG0gbQnyw2g HTTP/1.1" 200 None
2020-11-01 18:57:29,921 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:30,128 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/r7z65v8cnBP0MhGP4oQ0bQ HTTP/1.1" 200 None
2020-11-01 18:57:30,136 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:30,367 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/M8xnlKQOh0tl58LJCnPUVA HTTP/1.1" 200 None
2020-11-01 18:57:30,375 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:30,575 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/rVJNWn99tF1Jf1l01iFp_A HTTP/1.1" 200 None
2020-11-01 18:57:32,526 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:32,791 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw HTTP/1.1" 200 None
2020-11-01 18:57:32,794 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.yelp.com:443
2020-11-01 18:57:33,014 urllib3.connectionpool DEBUG    https://api.yelp.com:443 "GET /v3/businesses/ZhwXNucu2sV9XfILoXbNjw/reviews HTTP/1.1" 200 None
2020-11-01 18:57:33,054 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 18:57:33,077 django.request WARNING  Not Found: /restaurant/static/css/style.css
2020-11-01 18:58:29,244 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-11-01 18:58:29,244 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 18:58:29,990 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 18:58:50,929 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\forms.py changed, reloading.
2020-11-01 18:58:50,930 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 18:58:51,711 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 18:59:01,354 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-11-01 18:59:01,355 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 18:59:02,125 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 18:59:05,569 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\forms.py changed, reloading.
2020-11-01 18:59:05,570 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 18:59:06,319 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 19:48:44,850 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-11-01 19:48:44,853 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 19:48:45,789 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 19:50:35,518 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\views.py changed, reloading.
2020-11-01 19:50:35,519 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 19:50:36,328 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 20:06:17,405 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\dinesafelysite\settings.py changed, reloading.
2020-11-01 20:06:17,406 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 20:06:18,154 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 20:06:44,232 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\dinesafelysite\settings.py changed, reloading.
2020-11-01 20:06:44,233 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 20:06:44,998 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-11-01 20:08:08,821 django.utils.autoreload INFO     C:\Users\Legen\Documents\NYU\Software Engineering\dine-safe-ly\restaurant\models.py changed, reloading.
2020-11-01 20:08:08,822 asyncio      DEBUG    Using proactor: IocpProactor
2020-11-01 20:08:09,563 django.utils.autoreload INFO     Watching for file changes with StatReloader
